mybatis:
  # xml file location
  mapper-locations: classpath:mapper/*.xml
  # The location of the entity class
  type-aliases-package: com.liz.workspace.domain

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
