mybatis:
  # xml file location
  mapper-locations: classpath:mapper/*.xml
  # The location of the entity class
  type-aliases-package: com.liz.workspace.domain
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/board?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


  devtools:
    livereload:
      enabled: true

    # logging
#    logging:
#      config: classpath:logback-spring.xml
#      level:
#        org.springframework.security: DEBUG



