mybatis:
  # xml file location
  mapper-locations: classpath:mapper/*.xml
  # The location of the entity class
  type-aliases-package: com.liz.workspace.domain
  configuration:
    map-underscore-to-camel-case: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:log4jbdc:mysql://localhost:3306/board?
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: 1234



